# Generated by Django 4.2.3 on 2023-08-06 23:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_alter_auctionlistings_bids'),
    ]

    operations = [
        migrations.RenameField(
            model_name='auctionlistings',
            old_name='bids',
            new_name='bid',
        ),
    ]
