# Generated by Django 4.2.3 on 2023-08-07 12:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_rename_bids_auctionlistings_bid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auctionlistings',
            name='bid',
        ),
        migrations.AddField(
            model_name='bids',
            name='auctionListing',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='listing', to='auctions.auctionlistings'),
            preserve_default=False,
        ),
    ]
