# Generated by Django 4.2.3 on 2023-08-07 14:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_remove_auctionlistings_bid_bids_auctionlisting'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bids',
            old_name='listingBid',
            new_name='bid',
        ),
        migrations.AlterField(
            model_name='bids',
            name='auctionListing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auctionListingBid', to='auctions.auctionlistings'),
        ),
        migrations.AlterField(
            model_name='bids',
            name='userBid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userBid', to=settings.AUTH_USER_MODEL),
        ),
    ]
