# Generated by Django 4.2.3 on 2023-08-07 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_rename_listingbid_bids_bid_alter_bids_auctionlisting_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comments',
            name='likes',
        ),
    ]
