# Generated by Django 4.2.3 on 2023-08-08 13:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_remove_comments_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctionlistings',
            name='watchlist',
            field=models.ManyToManyField(blank=True, null=True, related_name='watchlist', to=settings.AUTH_USER_MODEL),
        ),
    ]
